spawn:
  ==: org.bukkit.Location
  world: world
  x: 0.5
  y: 100.0
  z: 0.5
  pitch: 0.0
  yaw: 0.0

warzone:
  ==: org.bukkit.Location
  world: world
  x: 100.5
  y: 70.0
  z: 100.5
  pitch: 0.0
  yaw: 0.0

crates:
  ==: org.bukkit.Location
  world: world
  x: 200.5
  y: 70.0
  z: 200.5
  pitch: 0.0
  yaw: 0.0