name: GrassGGChat
version: 1.0
main: me.sbpro.grassggchat.GrassGGChat
api-version: '26.2'

commands:
  chatcolor:
    description: Change your chat color
    usage: /chatcolor
    permission: grassgg.chatcolor.command

permissions:

  grassgg.chatcolor.command:
    default: true

  grassgg.chatcolor.bold:
    default: op

  grassgg.chatcolor.white:
    default: true

  grassgg.chatcolor.gray:
    default: op

  grassgg.chatcolor.black:
    default: op

  grassgg.chatcolor.red:
    default: op

  grassgg.chatcolor.orange:
    default: op

  grassgg.chatcolor.yellow:
    default: op

  grassgg.chatcolor.lime:
    default: op

  grassgg.chatcolor.green:
    default: op

  grassgg.chatcolor.aqua:
    default: op

  grassgg.chatcolor.blue:
    default: op

  grassgg.chatcolor.purple:
    default: op

  grassgg.chatcolor.pink:
    default: op

  grassgg.chatcolor.dark_gray:
    default: op

  grassgg.chatcolor.dark_aqua:
    default: op