name: GrassGGProtect
version: 1.0.0
main: me.sbpro.grassggprotect.GrassGGProtect
api-version: '1.21'
author: SBPro
description: Lightweight spawn and lobby protection plugin.

commands:
  grassggprotect:
    description: GrassGGProtect administration command.
    usage: /grassggprotect reload
    permission: grassgg.admin

permissions:
  grassgg.builder:
    default: op
    description: Builder perms for spawns
