name: GrassGGMissions
version: 1.0.0
authors: [ SBPro ]

main: me.sbpro.grassggmissions.GrassGGMissions
api-version: '26.2'
load: POSTWORLD
depend:
  - Vault

commands:
  dailymissions:
    aliases:
      - daily
      - dm

permissions:
  grassgg.missions.use:
    default: true
  grassgg.missions.admin:
    default: op