name: GrassGGHomes
version: '${version}'

main: me.sbpro.grassgghomes.GrassGGHomes
api-version: '1.21.11'
load: POSTWORLD

authors: [ SBPro ]

commands:
  homes:
    description: Opens and manages homes
    usage: /homes [home/player]
    aliases:
      - home

  sethome:
    description: Creates a home
    usage: /sethome <name>
    aliases:
      - createhome

  delhome:
    description: Deletes a home
    usage: /delhome <name>
    aliases:
      - deletehome

permissions:
  grassgg.homes.staff:
    default: op

  grassgg.homes.1:
    default: true
  grassgg.homes.2:
    default: true
  grassgg.homes.3:
    default: op
  grassgg.homes.4:
    default: op
  grassgg.homes.5:
    default: op
  grassgg.homes.6:
    default: op
  grassgg.homes.7:
    default: op