name: GrassGGHub
description: $description
version: '${version}'

main: me.sbpro.grassgghub.GrassGGHub
api-version: '26.2'
load: POSTWORLD

authors: [ SBPro ]

permissions:
  grassgg.staff:
    default: op