name: GrassGGSpawns
version: 1.0.0
main: me.sbpro.grassggspawns.GrassGGSpawns
api-version: '1.21'
author: SBPro
description: Lightweight spawn and lobby protection plugin.

commands:
  grassggspawns:
    description: GrassGGSpawns administration command.
    usage: /grassggspawns reload
    permission: grassgg.admin

permissions:
  grassgg.builder:
    default: op
    description: Builder perms for spawns
