name: GrassGGAnnouncements
version: 1.0.0
main: me.sbpro.grassggannouncements.GrassGGAnnouncements
api-version: '26.2'

commands:
  announcements:
    description: Manage GrassGG announcements
    usage: /announcements reload
    permission: grassggannouncements.admin
  announce:
    description: Sends an announcement to the server
    usage: /announce <announcement>
    permission: grassgg.announce
  livestream:
    aliases:
      - livestreamannounce
      - announcelivestream
      - stream
    permission: grassgg.media.announce
  content:
    aliases:
      - contentannounce
      - announce  content
      - video
      - short
    permission: grassgg.media.announce


permissions:
  grassggannouncements.admin:
    description: Allows management of GrassGG announcements
    default: op
  grassgg.announce:
    description: Allows the player to send server announcements
    default: op
  grassgg.media.announce:
    default: op
    description: Allows a media rank or above use /livestream.